In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [54]:
# VoxelSpace algorithm

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

color_img = Image.open("data/maps/C1W.png")
height_img = Image.open("data/maps/D1.png")

COLOR_MAP = color_img.load()
HEIGHT_MAP = height_img.load()

PAL = color_img.palette.getdata()[1]

print(COLOR_MAP)

def draw_vertical_line(x, ytop, ybottom, c):
    if ytop >= ybottom:
        return

    if ytop < 0:
        typ = 0
    
    

def render(x=0, y=0, phi=0, height=50, horizon=120, scale_height=120, distance=300, screen_width=800, screen_height=600):
    image = np.zeros((screen_width, screen_height, 3))
    ybuffer = np.full(screen_width, screen_height)
    
    dz = 1
    z = 1

    while z < distance:
        left_x  = -z*np.cos(phi) - z*np.sin(phi) + x
        left_y  =  z*np.sin(phi) - z*np.cos(phi) + y
        right_x =  z*np.cos(phi) - z*np.sin(phi) + x
        right_y = -z*np.sin(phi) - z*np.cos(phi) + y

        dx = (right_x - left_x) / screen_width
        dy = (right_y - left_y) / screen_width

        for i in range(screen_width):
            height_on_screen = (height - HEIGHT_MAP[left_x, left_y]) / z*scale_height + horizon
            draw_vertical_line(i, height_on_screen, ybuffer[i], COLOR_MAP[left_x, left_y])

            if height_on_screen < ybuffer[i]:
                ybuffer[i] = height_on_screen
            
            left_x += dx
            left_y += dy
        
        z += dz
        dz += 0.2

    return image

img = render()
plt.imshow(img)

[[[44 88 72]
  [44 84 68]
  [44 88 72]
  ...
  [44 88 72]
  [44 84 68]
  [44 88 72]]

 [[44 88 72]
  [56 84 80]
  [44 88 72]
  ...
  [44 88 72]
  [44 84 68]
  [52 96 76]]

 [[56 84 80]
  [56 84 80]
  [56 88 84]
  ...
  [44 84 68]
  [52 96 76]
  [56 88 84]]

 ...

 [[44 88 72]
  [44 84 68]
  [44 88 72]
  ...
  [44 88 72]
  [44 84 68]
  [44 88 72]]

 [[44 88 72]
  [44 84 68]
  [44 88 72]
  ...
  [44 88 72]
  [44 84 68]
  [44 88 72]]

 [[44 88 72]
  [44 84 68]
  [44 88 72]
  ...
  [44 88 72]
  [44 84 68]
  [44 88 72]]]


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices